# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kcmutils

# >> macros
# << macros

Summary:    KDE Frameworks 5 Tier 3 addon for interacting with KCModules
Version:    5.3.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kcmutils.yaml
Source101:  kcmutils-rpmlintrc
Requires:   kf5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kitemviews-devel
BuildRequires:  kconfigwidgets-devel
BuildRequires:  kcoreaddons-devel
BuildRequires:  ki18n-devel
BuildRequires:  kiconthemes-devel
BuildRequires:  kservice-devel
BuildRequires:  kxmlgui-devel

%description
KDE Frameworks 5 Tier 3 addon for interacting with KCModules


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kitemviews-devel
Requires:   kconfigwidgets-devel
Requires:   kcoreaddons-devel
Requires:   ki18n-devel
Requires:   kiconthemes-devel
Requires:   kservice-devel
Requires:   kxmlgui-devel

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%find_lang kcmutils5_qt --with-qt --all-name || :

%files -f kcmutils5_qt.lang
%defattr(-,root,root,-)
%doc COPYING.LIB README.md
%{_kf5_libdir}/libKF5KCMUtils.so.*
%{_kf5_servicetypesdir}/*.desktop
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_kf5_includedir}/kcmutils_version.h
%{_kf5_includedir}/KCMUtils
%{_kf5_libdir}/libKF5KCMUtils.so
%{_kf5_cmakedir}/KF5KCMUtils
%{_kf5_mkspecsdir}/qt_KCMUtils.pri
# >> files devel
# << files devel
